FIX: Always store the default field to support highlighting
silverstripe/silverstripe-fulltextsearch pull request #294
Opened 2021-02-24 03:54 UTC by GuySartorelli

Fixes #249

2021-05-14 10:24 UTC, dhensby requested changes
This isn't the right fix. `getStoredDefault()` is where the value is drawn from and that has the environment type check.

I don't know why it's true for dev envs only, but that's where the logic needs to be fixed

2021-05-16 07:00 UTC, michalkleiner commented
@dhensby `getStoredDefault` provides the information to all field type definitions, not just the default one. The logic there can stay as is, but for the default field, to enable highlighting, it needs to be stored regardless of the environment type, so changing it in this single place makes sense, unless there's another method introduces just for storing the default field.

My guess why it's stored for dev env only is to inspect the indexed records' content which you may not need in test/live environments.

2021-05-16 16:01 UTC, dhensby approved these changes

2021-05-16 23:27 UTC, GuySartorelli commented
@michalkleiner That's exactly what I was thinking. Thanks for putting it into words :)
There is an unfortunately lack of lexical distinction here between the default search field and the default value for 'stored'... could that be worth raising to avoid this sort of confusion going forward?

2021-08-05 21:53 UTC, merged